//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopifyW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        public int PriceID { get; set; }
        public int ItemID { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Unit { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
