//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopifyW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialOfferItem
    {
        public int SItemID { get; set; }
        public int OfferID { get; set; }
        public int ItemID { get; set; }
        public string Quantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SpecialOffer SpecialOffer { get; set; }
    }
}
